# Regex patterns for PII detection in Japanese text
# Each pattern has a name, regex, and optional description

patterns:
  - name: phone_number
    regex: '0\d{1,3}-\d{1,4}-\d{4}(?!\d)'
    description: "Japanese phone number (e.g., 03-1234-5678, 090-1234-5678)"
    
  - name: postal_code
    regex: '(?<![0-9-])\d{3}-\d{4}(?![0-9-])'
    description: "Japanese postal code (e.g., 150-0002)"
    
  - name: mynumber
    regex: '(?<!\d)\d{12}(?!\d)'
    description: "My Number (12 digits)"
    
  - name: credit_card
    regex: '\d{4}[\s-]?\d{4}[\s-]?\d{4}[\s-]?\d{4}'
    description: "Credit card number"
    
  - name: email
    regex: '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}'
    description: "Email address"
    
  - name: bank_account
    regex: '\d{4}-\d{3}-\d{7}'
    description: "Japanese bank account number format"